### ISSUE TITLE
Problem of Lack of Descriptions of Feeds... Thanks you.

### ISSUE THREAD

**Issue by ghost** [nvdaes/readFeeds#10]
Sorry. This new version of ReadFeeds, 10.10-dev, solved the problem of lack of
descriptions of Google's feeds, but now the ReadFeeds spent no more show
all other descriptions for the other feeds, like Google News, BBC, etc
... If you can take a look at this, I thank you again ... Thanks.

**Comment by nvdaes** [comment]
I will look at this, we may add check box or combo box to select the type of description. Thanks.

**Comment by ghost** [comment]
Ok... Thanks.

**Comment by nvdaes** [comment]
@AntonioCezar , can you test this new version? I addressed Google alerts, since imothis is better fixed in a case basis, that is, trying to get description articles according to RSS and Atom specifications, and, if possible and needed, addressing particular cases that may not fit these specs.
If this fixes this issue, I'll close it and share this new pre-release on the add-ons mailing list.
Thanks

https://github.com/nvdaes/readFeeds/releases/download/10.11-dev/readFeeds-10.11-dev.nvda-addon

**Comment by ghost** [comment]
Hello. This new 10.11-DEV version of the Read of Feeds worked very well and read the descriptions without problems for all the feeds that I accompany. But she demanded that I remove the old version 10.8-dev that I had installed here because it gave a mistake in the NVDA that he did not start anymore. I could not generate a log because when I removed the readfeds so that the NVDA could start and I could set up the log for debugging, after I reinstalled ReadFeeds 10.11-DEV, the NVDA returned to restart smoothly. Then here is the alert on removing old versions of READFEESD so that the common user does not run out of a screen reader after updating the readfeeds. My gratitude for your work and dedication in the development and maintenance of add-ons to the NVDA community ... Thank you.

**Comment by nvdaes** [comment]
Hello, I haven't observer problems when updating this add-on. Then, I will close this issue and will post this pre-release on the add-ons mailing list. Please, if you feel that users have to be warned about old versions, feel free to reply on the add-ons mailing list.
Thanks
