### ISSUE TITLE
[Feature]: Search field after opening a very large feed.

### ISSUE THREAD

**Issue by Lo-lo78** [nvdaes/readFeeds#38]
### Problem

The problem that a search is missing within a feed. It can be useful in very large feeds.

### Suggestion

Hi Noelia.
I found myself with a feed with more than 200 titles.
I was looking for a title and I realized that perhaps a search field inside the feed could be very useful.
It would be very nice that when you open a feed there is a search like in the main list of feeds.
The feed search appears only if you open a feed and could always be linked to the alt+f shortcut.
Thank you!

**Comment by nvdaes** [comment]
Hi @Lo-lo78 :
Thanks for your suggestion! Anyway, have you tried to open the feed as HTML? Then you can use `control+NVDA+f` in browse mode to search text, or `NVDA+f7`, then select headings and use the filter field. Is not enough for you? What do you think?
I'll wait for your reply before proceedingto implement this in the list of articles, since it may make the dialog more complicated and,  if it's not needed, I think it's better to keep dialogs as simple as possible.

**Comment by Lo-lo78** [comment]
@nvdaes 
You're right!
It can always be opened in HTML.
Thanks for the reply.
